// TODO Implement this library.// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWZXcoucH1C-94lg1WmnCp-dz5df3Z62E',
    appId: '1:946131721618:web:a512f6a08211e38777754b',
    messagingSenderId: '946131721618',
    projectId: 'firestore-cloud-d36e3',
    authDomain: 'firestore-cloud-d36e3.firebaseapp.com',
    storageBucket: 'firestore-cloud-d36e3.appspot.com',
    measurementId: 'G-1HTY8Q7HML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKyOAAif3Uv-ZB6kqhy6Wbxs_d1FPuoxc',
    appId: '1:946131721618:android:f921337b24c394fa77754b',
    messagingSenderId: '946131721618',
    projectId: 'firestore-cloud-d36e3',
    storageBucket: 'firestore-cloud-d36e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJZLv7rR70r12YIUN3OKlnSt_j9F7QDGc',
    appId: '1:946131721618:ios:cb4888088890dba077754b',
    messagingSenderId: '946131721618',
    projectId: 'firestore-cloud-d36e3',
    storageBucket: 'firestore-cloud-d36e3.appspot.com',
    iosBundleId: 'com.example.firestoreCloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJZLv7rR70r12YIUN3OKlnSt_j9F7QDGc',
    appId: '1:946131721618:ios:592dbdeb9a09e97277754b',
    messagingSenderId: '946131721618',
    projectId: 'firestore-cloud-d36e3',
    storageBucket: 'firestore-cloud-d36e3.appspot.com',
    iosBundleId: 'com.example.firestoreCloud.RunnerTests',
  );
}
